spring:
  application:
    name: msvc-gateway
  config:
    # this is the path where the configuration file is located and the port where the config server is running
    import: optional:configserver:http://localhost:8888
