server:
  # normally the port is 8888 but it can be any
  port: 8888

spring:
  # normally we can have a profile for each environment (dev, qa, prod, etc)
  profiles:
    # here we are telling it to use the native profile with which spring works
    active: native
  application:
    # application name
    name: config-server
  cloud:
    # path where the configuration files are located
    config:
      server:
        native:
          # we indicate that the path of the configuration files are in the 'configurations' folder
          search-locations: classpath:/configurations
