# we do this to make sure that the gateway is not registered with the eureka server
eureka:
  client:
    register-with-eureka: false

server:
  # the gateway runs on port 8080 because that is where we will make all the requests
  port: 8080

spring:
  application:
    # name of the gateway
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        # we enable the gateway
        locator:
          enabled: true
          # we configure the gateway to know where to redirect requests
      routes:
        # the id is simply an identifier for the route
        - id: students
            # the uri is the path where the requests will be redirected
          uri: http://localhost:8090
          # the predicate is the condition that the request must meet in order to be redirected
          predicates:
            - Path=/api/student/**
          # we configure another route for another different microservice doing the same as with the previous one
        - id: courses
          uri: http://localhost:9090
          predicates:
            - Path=/api/course/**
