# Configuraci贸n Eureka
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://micro-eureka-compose:8761/eureka

# Configuraci贸n del servidor de la puerta de enlace
server:
  port: 8080

# Configuraci贸n de la aplicaci贸n Spring
spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://micro-student-compose:8030
          predicates:
            - Path=/api/student/**

        - id: courses
          uri: http://micro-course-compose:8010
          predicates:
            - Path=/api/course/**
        - id: security
          uri: http://micro-security-compose:8020
          predicates:
            - Path=/api/auth/**
            - Path=/api/user/**
