# we have to respect all the spaces and indentation in the file otherwise it will not work
server:
  # this is the deault port for eureka server
  port: 8761

spring:
  application:
    # name of the application
    name: msvc-eureka
# configuration of eureka
eureka:
  instance:
    # this is the host where eureka will run
    hostname: localhost
  client:
    # with this we avoid that eureka registers itself in the eureka server
    register-with-eureka: false
    # with this we avoid that eureka fetches the registry from the eureka server
    fetch-registry: false
    # with this we indicate the path in which the eureka server will work
    server-url:
      defaultZone: http://localhost:${server.port}/eureka/
