server:
  port: 8010

spring:
  application:
    name: msvc-course
  datasource:
    driver-class-name: ${DATABASE_DRIVER_CLASS_NAME}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: micro-eureka-compose
  client:
    service-url:
      defaultZone: http://micro-eureka-compose:8761/eureka
