server:
  port: 8030

spring:
  application:
    name: msvc-student
  datasource:
    driver-class-name: ${DATABASE_DRIVER_CLASS_NAME}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    # jpa configuration
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
# with this we will register this microservice in the eureka discovery server
eureka:
  instance:
    hostname: micro-eureka-compose
  client:
    service-url:
      defaultZone: http://micro-eureka-compose:8761/eureka
